apiVersion: v1
kind: Service
metadata:
  labels:
    app: admindatasource
    environment: Development
  name: admindatasource
  namespace: spot-services
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: admindatasource
  sessionAffinity: None
  type: ClusterIP
