name: CI test build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Get current time
        uses: MyJetTools/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
          utcOffset: "+00:00"

      - name: Build
        run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ github.run_number }}
      - name: Test
        run: dotnet test --no-build --configuration Release
      - name: ls
        run: ls

      - name: Publish Service
        run: dotnet publish --no-build ./src/Service.Trading/Service.Trading.csproj --configuration Release --output ./publish-api

      - name: Check Service dir
        run: ls ./publish-api

      - name: Publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: ./publish-api
          registry: docker.pkg.github.com
          repository: ${{ secrets.ORG_NAME }}/service.trading/service.trading
          tags: latest
          build_args: app_version=myjetwallet.service.registration-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

