name: Release API client nuget

on:
  push:
    tags: "client-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  

    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/client-}

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Create the package
      run: dotnet pack --configuration Release src/Service.Trading.Client /p:Version=${GITHUB_REF#refs/tags/client-}

    - name: Publish the package to GitHub
      uses: MyJetWallet/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  './src/Service.Trading.Client/bin/Release/*.nupkg'
        repo-owner:  'myjetwallet'
        gh-user:  ${{ github.actor }}
        token:  ${{ secrets.GITHUB_TOKEN }}  

